; Note: The content of this file and keycodes.bb will eventually by baked into Blitz3D runtime.dll

#EVENT_MASK_CLOSE_CLICKED = $01
#EVENT_MASK_SIZE_CHANGED  = $02
#EVENT_MASK_LOST_FOCUS    = $04
#EVENT_MASK_GOT_FOCUS     = $08
#EVENT_MASK_SUSPENDED     = $10
#EVENT_MASK_RESUMED       = $20

#WINDOW_STATE_CLOSED      = 0
#WINDOW_STATE_MINIMIZED   = 1
#WINDOW_STATE_NORMAL      = 2
#WINDOW_STATE_MAXIMIZED   = 3
#WINDOW_STATE_FULLSCREEN  = 4

#WINDOW_FLAGS_NONE        = $00
#WINDOW_FLAGS_FULLSCREEN  = $01
#WINDOW_FLAGS_RESIZABLE   = $02
#WINDOW_FLAGS_CENTERED    = $04

#MOUSE_CURSOR_MODE_NORMAL   = 1
#MOUSE_CURSOR_MODE_HIDDEN   = 2
#MOUSE_CURSOR_MODE_DISABLED = 3
#MOUSE_CURSOR_MODE_CAPTURED = 4

#TEXTURE_FORMAT_ANY      = 0
#TEXTURE_FORMAT_R8       = 1
#TEXTURE_FORMAT_RG8      = 2
#TEXTURE_FORMAT_RGBA8    = 3
#TEXTURE_FORMAT_SRGBA8   = 4
#TEXTURE_FORMAT_R8S      = 5
#TEXTURE_FORMAT_RG8S     = 6
#TEXTURE_FORMAT_RGBA8S   = 7
#TEXTURE_FORMAT_R16F     = 8
#TEXTURE_FORMAT_RG16F    = 9
#TEXTURE_FORMAT_RGBA16F  = 10

#TEXTURE_FLAGS_NONE    = $00
#TEXTURE_FLAGS_CLAMP_U = $01
#TEXTURE_FLAGS_CLAMP_V = $02
#TEXTURE_FLAGS_CLAMP_W = $04
#TEXTURE_FLAGS_CLAMP   = $07
#TEXTURE_FLAGS_FILTER  = $08
#TEXTURE_FLAGS_MIPMAP  = $10
#TEXTURE_FLAGS_DEFAULT = $18
#TEXTURE_FLAGS_IMAGE   = $1f

#BLEND_MODE_OPAQUE      = 1
#BLEND_MODE_ALPHA_MASK  = 2
#BLEND_MODE_ALPHA_BLEND = 3

#DEPTH_FUNC_NEVER         = 1
#DEPTH_FUNC_LESS          = 2
#DEPTH_FUNC_EQUAL         = 3
#DEPTH_FUNC_LESS_EQUAL    = 4
#DEPTH_FUNC_GREATER       = 5
#DEPTH_FUNC_NOT_EQUAL     = 6
#DEPTH_FUNC_GREATER_EQUAL = 7
#DEPTH_FUNC_ALWAYS        = 8

#CULL_MODE_NONE  = 1
#CULL_MODE_FRONT = 2
#CULL_MODE_BACK  = 3

#IMAGE_VIEW_MODE_FIXED   = 1
#IMAGE_VIEW_MODE_FREE    = 2
#IMAGE_VIEW_MODE_UPRIGHT = 3

#ANIMATION_MODE_ONE_SHOT  = 1
#ANIMATION_MODE_LOOP      = 2
#ANIMATION_MODE_PING_PONG = 3

#COLLISION_RESPONSE_NONE =    0
#COLLISION_RESPONSE_STOP =    1
#COLLISION_RESPONSE_SLIDE =   2
#COLLISION_RESPONSE_SLIDEXZ = 3

; IDE Options = PureBasic 6.12 LTS (Windows - x64)
; CursorPosition = 75
; EnableAsm
; EnableXP
; DPIAware